root: ./

​structure:
    readme: README.md
    summary: SUMMARY.md

redirects:
getting-started/upgrading: upgrading/upgrade.md
getting-started/upgrading/version-specific: upgrading/version-specific.md
getting-started/installation: installation/installation.md
getting-started/licensing-model: installation/licensing-model.md
guides/migrating-from-konstrukt-to-umbraco-ui-builder: upgrading/migrating-from-konstrukt-to-umbraco-ui-builder.md
