root: ./

structure:
    readme: README.md
    summary: SUMMARY.md

redirects:
    getting-started/configuration: getting-started/first-profile.md
    management-api/chat/stream: management-api/chat/complete.md
