root: ./

​structure:
    readme: README.md
    summary: SUMMARY.md

redirects:
    fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/rich-text-editor-tinymce: fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/rich-text-editor/README.md
    fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/rich-text-editor-tinymce/configuration: fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/rich-text-editor/configuration.md
    fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/rich-text-editor-tinymce/styles: fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/rich-text-editor/README.md
    fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/rich-text-editor-tinymce/plugins: fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/rich-text-editor/extensions.md
    fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/rich-text-editor-tinymce/blocks: fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/rich-text-editor/blocks.md
    fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/rich-text-editor/change-rich-text-editor-ui: fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/rich-text-editor/README.md
    customizing/development-flow/typescript-setup: customizing/development-flow/README.md
    customizing/foundation/working-with-data: customizing/foundation/README.md
    customizing/foundation/working-with-data/context-api: customizing/foundation/context-api/README.md
    customizing/foundation/working-with-data/repositories: customizing/foundation/repositories.md
    customizing/foundation/working-with-data/states: customizing/foundation/states.md
    customizing/foundation/working-with-data/store: customizing/foundation/README.md
    fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/rich-text-editor/blocks: fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/rich-text-editor/README.md
    tutorials/creating-a-custom-dashboard: tutorials/creating-a-custom-dashboard/README.md
    extending/property-editors/declaring-your-property-editor: tutorials/creating-a-property-editor/README.md
    reference/management/services/create-a-new-user: reference/management/using-services/userservice.md
    reference/management/services/auditservice: reference/management/README.md
    reference/management/services/contentservice: reference/management/README.md
    reference/management/services/contenttypeservice: reference/management/README.md
    reference/management/services/contenttypeservice/retrieving-content-type-containers: reference/management/using-services/contenttypeservice.md
    reference/management/services/datatypeservice: reference/management/README.md
    reference/management/services/domainservice: reference/management/README.md
    reference/management/services/entityservice: reference/management/README.md
    reference/management/services/externalloginservice: reference/management/README.md
    reference/management/services/fileservice: reference/management/README.md
    reference/management/services/localizationservice: reference/management/README.md
    reference/management/services/macroservice: reference/management/README.md
    reference/management/services/membergroupservice: reference/management/README.md
    reference/management/services/memberservice: reference/management/README.md
    reference/management/services/membertypeservice: reference/management/README.md
    reference/management/services/notificationservice: reference/management/README.md
    reference/management/services/packagingservice: reference/management/README.md
    reference/management/services/publicaccessservice: reference/management/README.md
    reference/management/services/redirecturlservice: reference/management/README.md
    reference/management/services/serverregistrationservice: reference/management/README.md
    reference/management/services/tagservice: reference/management/README.md
    reference/management/services/textservice: reference/management/README.md
    reference/management/services/userservice: reference/management/using-services/userservice.md
    reference/management/models: reference/management/README.md
    reference/management/models/content: reference/management/README.md
    reference/management/models/contenttype: reference/management/README.md
    reference/management/models/datatype: reference/management/README.md
    reference/management/models/dictionaryitem: reference/management/README.md
    reference/management/models/language: reference/management/README.md
    reference/management/models/media: reference/management/README.md
    reference/management/models/mediatype: reference/management/README.md
    reference/management/models/relation: reference/management/README.md
    reference/management/models/relationtype: reference/management/README.md
    reference/management/models/serverregistration: reference/management/README.md
    reference/management/models/template: reference/management/README.md
    reference/management/services: reference/management/using-services/README.md
    reference/management/services/consentservice: reference/management/using-services/consentservice.md
    reference/management/services/mediaservice: reference/management/using-services/mediaservice.md
    reference/management/services/relationservice: reference/management/using-services/relationservice.md
    reference/management/services/contentservice/create-content-programmatically: reference/management/using-services/contentservice.md
    reference/management/services/create-content-programmatically: reference/management/using-services/contentservice.md
    reference/management/services/contenttypeservice/retrieving-content-types: reference/management/using-services/contenttypeservice.md
    reference/management/services/retrieving-content-types: reference/management/using-services/contenttypeservice.md
    reference/management/services/localizationservice/retrieving-languages: reference/management/using-services/localizationservice.md
    reference/management/services/retrieving-languages: reference/management/using-services/localizationservice.md
    reference/management/services/managing-users: reference/management/using-services/userservice.md
    reference/management/services/userservice/create-a-new-user: reference/management/using-services/userservice.md
    reference/angular: customizing/ui-library.md
    reference/angular/directives: customizing/ui-library.md
    reference/angular/directives/umbproperty: customizing/ui-library.md
    reference/angular/directives/umbloadindicator: customizing/ui-library.md
    reference/angular/directives/umblayoutselector: customizing/ui-library.md
    reference/angular/services: customizing/ui-library.md
    reference/angular/services/editorservice: customizing/ui-library.md
    reference/angular/services/eventsservice: customizing/ui-library.md
    reference/angular/services/eventsservice/changetitle: customizing/ui-library.md
    extending-backoffice/content-apps: customizing/extending-overview/extension-types/workspaces/workspace-views.md
    extending-backoffice/localization: customizing/extending-overview/extension-types/localization.md
    extending/ui-library: customizing/ui-library.md
    extending/backoffice-ui-api-documentation: customizing/ui-library.md
    reference/configuration/richtexteditorsettings: fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/rich-text-editor/configuration.md
    extending-backoffice/section-trees/trees/tree-actions: customizing/extending-overview/extending-types/entity-actions.md
    extending/macro-parameter-editors: reference/templating/macros.md
    extending/health-check/guides/macroerrors: reference/templating/macros.md
    fundamentals/design/partial-view-macro-files: reference/templating/macros.md
    reference/templating/macros/managing-macros: reference/templating/macros.md
    reference/templating/macros/partial-view-macros: reference/templating/macros.md
    fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/nested-content: fundamentals/backoffice/property-editors/README.md
    fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/grid-layout/build-your-own-editor: fundamentals/backoffice/property-editors/README.md
    fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/grid-layout/grid-editors: fundamentals/backoffice/property-editors/README.md
    fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/grid-layout: fundamentals/backoffice/property-editors/README.md
    fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/grid-layout/add-value-programmatically: fundamentals/backoffice/property-editors/README.md
    fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/grid-layout/grid-editors/configuring-the-grid-layout-datatype: fundamentals/backoffice/property-editors/README.md
    fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/grid-layout/grid-editors/settings-and-styles: fundamentals/backoffice/property-editors/README.md
    fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/grid-layout/grid-editors/build-your-own-editor: fundamentals/backoffice/property-editors/README.md
    fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/grid-layout/grid-editors/render-grid-in-template: fundamentals/backoffice/property-editors/README.md
    fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/grid-layout/grid-editors/grid-layout-best-practices: fundamentals/backoffice/property-editors/README.md
    fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/grid-layout/grid-editors/what-are-grid-layouts: fundamentals/backoffice/property-editors/README.md
    fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/media-picker: fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/media-picker-3.md
    fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/multinode-treepicker: fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/content-picker.md
    reference/notifications/contentypeservice-notifications: reference/notifications/README.md
    reference/notifications/datatypeservice-notifications: reference/notifications/README.md
    reference/notifications/fileservice-notifications: reference/notifications/README.md
    reference/notifications/localizationservice-notifications: reference/notifications/README.md
    reference/notifications/mediatypeservice-notifications: reference/notifications/README.md
    reference/notifications/membertypeservice-notifications: reference/notifications/README.md
    reference/notifications/relationservice-notifications: reference/notifications/README.md
    tutorials/editors-manual/working-with-content/rich-text-editor: tutorials/editors-manual/working-with-content.md
    fundamentals/backoffice/content-templates: fundamentals/backoffice/document-blueprints.md
    reference/configuration/runtimeminificationsettings: reference/configuration/README.md
    reference/routing/umbraco-api-controllers/authorization: reference/routing/umbraco-api-controllers/README.md
    reference/routing/umbraco-api-controllers/routing: reference/routing/umbraco-api-controllers/README.md
    reference/notifications/sendingallowedchildrennotifications: reference/content-type-filters.md
    extending/property-editors/package-manifest: customizing/umbraco-package.md
    fundamentals/backoffice/infinite-editing: fundamentals/backoffice/sidebar.md
    extending/backoffice-tours: extending/build-on-umbraco-functionality.md
    tutorials/creating-a-backoffice-tour: tutorials/overview.md
    extending/packages/types-of-packages: extending/packages/README.md
    reference/configuration/nucachesettings: reference/configuration/cache-settings.md
    fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/listview: fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/collection.md
    fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/rich-text-editor/rte-styles: fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/rich-text-editor-tinymce/styles.md
    fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/rich-text-editor/rte-plugins: fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/rich-text-editor-tinymce/plugins.md
    fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/rich-text-editor/rte-blocks: fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/rich-text-editor-tinymce/blocks.md
    fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/block-editor/label-property-configuration: reference/umbraco-flavored-markdown.md
    customizing/property-editors/build-a-block-editor: fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/block-editor/README.md
    tutorials/creating-and-distributing-a-package: extending/packages/creating-a-package.md
    fundamentals/design/templates/named-sections: fundamentals/design/templates/README.md
    tutorials/custom-error-pages: tutorials/custom-error-page.md
    reference/events/contentservice-events: reference/notifications/contentservice-notifications.md
    reference/configuration-for-umbraco-7-and-8/webconfig: reference/configuration/README.md
    fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/block-editor/build-custom-view-for-blocks: tutorials/creating-custom-views-for-blocklist.md
    fundamentals/backoffice/property-editors/built-in-property-editors/rich-text-editor: fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/rich-text-editor/README.md
    fundamentals/backoffice/property-editors/built-in-property-editors/nested-content: fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/block-editor/README.md
    fundamentals/backoffice/property-editors/built-in-property-editors/block-list-editor: fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/block-editor/README.md
    extending/ui-documentation: customizing/README.md
    extending/section-trees/sections: umbraco-cms/customizing/extending-overview/extension-types/sections/section.md
    extending/property-editors: customizing/property-editors/README.md
    extending/language-files/ui-localization: customizing/foundation/localization.md
    extending/dashboards: customizing/extending-overview/extension-types/dashboard.md
    extending/customize-the-editing-experience: customizing/README.md
    extending/customize-backoffice/vite-package-setup: customizing/development-flow/vite-package-setup.md
    extending/customize-backoffice: customizing/README.md
    extending/content-apps: customizing/extending-overview/extension-types/workspaces/workspace-views.md
    extending/backoffice-setup/extension-types: customizing/extending-overview/extension-types/README.md
    customizing/extending-overview/extension-registry/extension-registry: customizing/extending-overview/extension-registry/register-extensions.md
    customizing/extending-overview/extension-types/workspaces/workspace-action-menu-item: customizing/extending-overview/extension-types/workspaces/workspace-action-menu-items.md
    customizing/extending-overview/extension-types/workspaces/workspace-footer-app: customizing/extending-overview/extension-types/workspaces/workspace-footer-apps.md
