---
extends: substitution
message: "Use '%s' instead of '%s' for brand consistency."
description: >
  Ensures consistent capitalization of brand and product names.
  This rule ignores matches inside markdown links and inline code to prevent false warnings.
link: https://docs.umbraco.com/contributing/documentation/style-guide#brands
level: warning
scope: text
ignorecase: true
# Sorted alphabetically for easier maintenance.
swap:
# Use negative lookbehind to ignore matches inside markdown links `[text](link)` or inline code `code`
  '(?<![\[`(])\bazure\b(?![.\w/-]*\))': "Azure"
  '(?<![\[`])\bazure devops\b': "Azure DevOps"
  '(?<![\[`])\bchrome\b': "Chrome"
  '(?<![\[`])\bcloudflare\b': "Cloudflare"
  '(?<![\[`])\bfirefox\b': "Firefox"
  '(?<![\[`\/\.])\bgitbook\b': "GitBook"
  '(?<![\[`])\bgithub\b': "GitHub"
  '(?<![\[`])\bmacos\b': "macOS"
  '(?<![\[`(])\bmicrosoft\b(?![.\w/-]*\))': "Microsoft"
  '(?<![\[`])\bnginx\b': "NGINX"
  '(?<![\[`])\bsafari\b': "Safari"
  '(?<![\[`])\bslack\b': "Slack"
  '(?<![\[`])\btwitter\b': "Twitter"
  '(?<![\[`])\bumbraco id\b': "Umbraco ID"
  '(?<![\[`])\bumbraco support\b': "Umbraco Support"
  '(?<![\[`])\bvisual studio code\b': "Visual Studio Code"
  '(?<![\[`])\bvs code\b': "Visual Studio Code"
  '(?<![\[`])\byoutube\b(?![-\.\/])': "YouTube"