---
extends: substitution
message: "We prefer %s over '%s.'"
level: warning
swap:
  '(?<![\.\/])youtube': "'YouTube'"
  microsoft: "'Microsoft'"
  slack: "'Slack'"
  azure: "'Azure'"
  gitbook: "'GitBook'"
  Gitbook: "'GitBook'"
  github: "'GitHub'"
  Github: "'GitHub'"
