--- 
extends: existence
message: "Consider removing '%s' as it can be considered opinionated."
description: >
  Flags words and phrases that express opinion, exaggeration, or assumptions. These can make documentation feel biased, subjective, or unclear.
link: https://docs.umbraco.com/contributing/documentation/style-guide#avoid-punctuation-in-headings
level: warning
ignorecase: true
# Sorted alphabetically for easier maintenance.
# Uses regex patterns with \b for whole word matching.
# The pattern for 'simple' excludes common technical terms to reduce false positives.
tokens:
  - actually
  - aptly
  - are a number
  - basically
  - clearly
  - completely
  - easy
  - easily
  - essentially
  - everybody knows
  - everyone knows
  - exceedingly
  - excellent
  - extremely
  - fairly
  - fortunately
  - huge
  - interestingly
  - is a number
  - it is important to realize
  - it should be noted that
  - just
  - largely
  - mostly
  - notably
  - note that
  - obviously
  - of course
  - quite
  - relatively
  - remarkably
  - several
  - significantly
  - '\bsimple\b(?! (Mail|Message|Object|Protocol|Transfer|Markup))'
  - simply
  - substantially
  - surprisingly
  - tiny
  - totally
  - tragically
  - unfortunately
  - untimely
  - various
  - vast
  - very
  - without a doubt
