--- 
extends: substitution
message: "Use '%s' instead of '%s' for consistency."
description: >
  Ensures consistent capitalization and formatting of common terms and acronyms.
link: https://docs.umbraco.com/contributing/documentation/style-guide#names
level: warning
scope: paragraph
swap:
  '\bcss\b(?!/)': CSS
  '(?<!\.)[hH]tml': HTML
  'url(?!=)': URL
  '(?:(?<!\.)js|[jJ]ava[sS]cript)': JavaScript
  '(?:(?<!\.)ts|[tT]ype[sS]cript)': TypeScript
  '.net': .NET
  'dot net': .NET
  '\bcms\b': CMS
  '[aA]ngular[jJ][sS]': AngularJS
  'SUITS': Sales
