---
extends: substitution
message: "Use %s instead of '%s' for consistency."
description: >
  Replaces outdated, unclear, or informal terms with more inclusive or formal alternatives
  for clarity, accessibility, and consistency across Umbraco documentation.
link: https://docs.umbraco.com/contributing/documentation/style-guide#terms-general
level: warning
ignorecase: true
swap:
  '\bmaster\s+(branch|template|templates|templating|view|views|layout|database|server)\b': "'primary $1'"
  '\bslave\b': "'secondary'"
  '\bblack\s?lists?\b': "'denylists'"
  '\bwhite\s?lists?\b': "'allowlists'"
  'etc': "'and so on'"
  '\be\.?g\.?,?': "'for example'"
  '\bi\.?e\.?,?': "'that is'"
  '\baka\b': "'also known as'"
  '\bdocs\b': "'documentation'"
