root: ./

​structure:  
    readme: README.md
    summary: SUMMARY.md

redirects:
    tutorials/add-azure-active-directory-authentication: tutorials/add-microsoft-entra-id-authentication.md
    fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/nested-content: fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/block-editor/block-list-editor.md
    tutorials/editors-manual/working-with-content/rich-text-editor: tutorials/editors-manual/working-with-content/README.md
    extending/packages/types-of-packages: extending/packages/README.md
    extending/property-editors/build-a-block-editor: fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/block-editor/README.md
    tutorials/creating-and-distributing-a-package: extending/packages/creating-a-package.md
    fundamentals/design/templates/razor-cheatsheet: fundamentals/design/templates/README.md
    reference/management-api: reference/dive-into-the-code.md
