root: ./

​structure:  
    readme: README.md
    summary: SUMMARY.md

redirects:
    tutorials/add-azure-active-directory-authentication: tutorials/add-microsoft-entra-id-authentication.md
    tutorials/editors-manual/working-with-content/rich-text-editor: tutorials/editors-manual/working-with-content.md
    extending/property-editors/build-a-block-editor: fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/block-editor/README.md
    tutorials/creating-and-distributing-a-package: extending/packages/creating-a-package.md
