id: Vendr.Contrib.PaymentProviders.Adyen
name: Adyen
logo: adyen.svg
type: PaymentProvider
supportedBy: community

packageVersion: 2.0.0
docVersions:
  next: 
  current: 2.0.0
  previous: 
    - 1.0.0

links:
  - title: Versions
    link: /versions/
  - title: Changelog
    link: /changelog/