root: ./

​structure:
    readme: README.md
    summary: SUMMARY.md

redirects:
    installing-workflow: installation/installing-workflow.md
    licensing: installation/licensing.md
    upgrading-workflow/migrating-workflow: upgrading/migrating-workflow.md
    upgrading-workflow/upgrading: upgrading/upgrading.md
