-- =============================================================================
-- Umbraco Engage: Clean up orphaned data for all foreign key constraints and enable/check them
-- =============================================================================
UPDATE t SET t.[projectId] = NULL FROM [umbracoEngageAbTestingAbTest] t WHERE t.[projectId] IS NOT NULL AND NOT EXISTS (SELECT 1 FROM [umbracoEngageAbTestingAbTestProject] r WHERE r.[id] = t.[projectId]);
UPDATE t SET t.[goalId] = NULL FROM [umbracoEngageAbTestingAbTest] t WHERE t.[goalId] IS NOT NULL AND NOT EXISTS (SELECT 1 FROM [umbracoEngageSettingsGoal] r WHERE r.[id] = t.[goalId]);
DELETE t FROM [umbracoEngageAbTestingAbTestContentType] t WHERE NOT EXISTS (SELECT 1 FROM [umbracoEngageAbTestingAbTest] r WHERE r.[id] = t.[abTestId]);
DELETE t FROM [umbracoEngageAbTestingAbTestUmbracoPageVariant] t WHERE NOT EXISTS (SELECT 1 FROM [umbracoEngageAbTestingAbTest] r WHERE r.[id] = t.[abTestId]);
DELETE t FROM [umbracoEngageAbTestingAbTestVariant] t WHERE NOT EXISTS (SELECT 1 FROM [umbracoEngageAbTestingAbTest] r WHERE r.[id] = t.[abTestId]);
DELETE t FROM [umbracoEngageAbTestingAbTestVisitorToVariant] t WHERE NOT EXISTS (SELECT 1 FROM [umbracoEngageAbTestingAbTest] r WHERE r.[id] = t.[abTestId]) OR NOT EXISTS (SELECT 1 FROM [umbracoEngageAnalyticsVisitor] r WHERE r.[id] = t.[visitorId]);
UPDATE t SET t.[abTestVariantId] = NULL FROM [umbracoEngageAbTestingAbTestVisitorToVariant] t WHERE t.[abTestVariantId] IS NOT NULL AND NOT EXISTS (SELECT 1 FROM [umbracoEngageAbTestingAbTestVariant] r WHERE r.[id] = t.[abTestVariantId]);
DELETE t FROM [umbracoEngageAnalyticsAnnotationPageVariant] t WHERE NOT EXISTS (SELECT 1 FROM [umbracoEngageAnalyticsAnnotation] r WHERE r.[id] = t.[annotationId]);
DELETE t FROM [umbracoEngageAnalyticsBrowserVersion] t WHERE NOT EXISTS (SELECT 1 FROM [umbracoEngageAnalyticsBrowser] r WHERE r.[id] = t.[browserId]);
UPDATE t SET t.[browserVersionId] = NULL FROM [umbracoEngageAnalyticsDevice] t WHERE t.[browserVersionId] IS NOT NULL AND NOT EXISTS (SELECT 1 FROM [umbracoEngageAnalyticsBrowserVersion] r WHERE r.[id] = t.[browserVersionId]);
UPDATE t SET t.[operatingSystemVersionId] = NULL FROM [umbracoEngageAnalyticsDevice] t WHERE t.[operatingSystemVersionId] IS NOT NULL AND NOT EXISTS (SELECT 1 FROM [umbracoEngageAnalyticsOperatingSystemVersion] r WHERE r.[id] = t.[operatingSystemVersionId]);
DELETE t FROM [umbracoEngageAnalyticsGoalCompletion] t WHERE NOT EXISTS (SELECT 1 FROM [umbracoEngageAnalyticsPageview] r WHERE r.[id] = t.[pageviewId]) OR NOT EXISTS (SELECT 1 FROM [umbracoEngageSettingsGoal] r WHERE r.[id] = t.[goalId]);
UPDATE t SET t.[locationId] = NULL FROM [umbracoEngageAnalyticsIpAddress] t WHERE t.[locationId] IS NOT NULL AND NOT EXISTS (SELECT 1 FROM [umbracoEngageAnalyticsIpLocation] r WHERE r.[id] = t.[locationId]);
DELETE t FROM [umbracoEngageAnalyticsIpLocation] t WHERE NOT EXISTS (SELECT 1 FROM [umbracoEngageAnalyticsIpCountry] r WHERE r.[id] = t.[countryId]);
UPDATE t SET t.[provinceId] = NULL FROM [umbracoEngageAnalyticsIpLocation] t WHERE t.[provinceId] IS NOT NULL AND NOT EXISTS (SELECT 1 FROM [umbracoEngageAnalyticsIpProvince] r WHERE r.[id] = t.[provinceId]);
UPDATE t SET t.[countyId] = NULL FROM [umbracoEngageAnalyticsIpLocation] t WHERE t.[countyId] IS NOT NULL AND NOT EXISTS (SELECT 1 FROM [umbracoEngageAnalyticsIpCounty] r WHERE r.[id] = t.[countyId]);
UPDATE t SET t.[cityId] = NULL FROM [umbracoEngageAnalyticsIpLocation] t WHERE t.[cityId] IS NOT NULL AND NOT EXISTS (SELECT 1 FROM [umbracoEngageAnalyticsIpCity] r WHERE r.[id] = t.[cityId]);
DELETE t FROM [umbracoEngageAnalyticsLinks] t WHERE NOT EXISTS (SELECT 1 FROM [umbracoEngageAnalyticsPageview] r WHERE r.[id] = t.[pageviewId]);
UPDATE t SET t.[pageId] = NULL FROM [umbracoEngageAnalyticsLinks] t WHERE t.[pageId] IS NOT NULL AND NOT EXISTS (SELECT 1 FROM [umbracoEngageAnalyticsPage] r WHERE r.[id] = t.[pageId]);
DELETE t FROM [umbracoEngageAnalyticsOperatingSystemVersion] t WHERE NOT EXISTS (SELECT 1 FROM [umbracoEngageAnalyticsOperatingSystem] r WHERE r.[id] = t.[operatingSystemId]);
UPDATE t SET t.[searchEngineId] = NULL FROM [umbracoEngageAnalyticsPage] t WHERE t.[searchEngineId] IS NOT NULL AND NOT EXISTS (SELECT 1 FROM [umbracoEngageAnalyticsSearchEngine] r WHERE r.[id] = t.[searchEngineId]);
DELETE t FROM [umbracoEngageAnalyticsPageEvent] t WHERE NOT EXISTS (SELECT 1 FROM [umbracoEngageAnalyticsPageview] r WHERE r.[id] = t.[pageviewId]);
DELETE t FROM [umbracoEngageAnalyticsPageview] t WHERE NOT EXISTS (SELECT 1 FROM [umbracoEngageAnalyticsPage] r WHERE r.[id] = t.[pageId]) OR NOT EXISTS (SELECT 1 FROM [umbracoEngageAnalyticsIpAddress] r WHERE r.[id] = t.[ipAddressId]);
UPDATE t SET t.[referrerPageId] = NULL FROM [umbracoEngageAnalyticsPageview] t WHERE t.[referrerPageId] IS NOT NULL AND NOT EXISTS (SELECT 1 FROM [umbracoEngageAnalyticsPage] r WHERE r.[id] = t.[referrerPageId]);
UPDATE t SET t.[sessionId] = NULL FROM [umbracoEngageAnalyticsPageview] t WHERE t.[sessionId] IS NOT NULL AND NOT EXISTS (SELECT 1 FROM [umbracoEngageAnalyticsSession] r WHERE r.[id] = t.[sessionId]);
UPDATE t SET t.[umbracoPageVariantId] = NULL FROM [umbracoEngageAnalyticsPageview] t WHERE t.[umbracoPageVariantId] IS NOT NULL AND NOT EXISTS (SELECT 1 FROM [umbracoEngageAnalyticsUmbracoPageVariant] r WHERE r.[id] = t.[umbracoPageVariantId]);
UPDATE t SET t.[appliedPersonalizationId] = NULL FROM [umbracoEngageAnalyticsPageview] t WHERE t.[appliedPersonalizationId] IS NOT NULL AND NOT EXISTS (SELECT 1 FROM [umbracoEngagePersonalizationAppliedPersonalization] r WHERE r.[id] = t.[appliedPersonalizationId]);
DELETE t FROM [umbracoEngageAnalyticsPageviewAbTestVariant] t WHERE NOT EXISTS (SELECT 1 FROM [umbracoEngageAnalyticsPageview] r WHERE r.[id] = t.[pageviewId]) OR NOT EXISTS (SELECT 1 FROM [umbracoEngageAbTestingAbTestVariant] r WHERE r.[id] = t.[abTestVariantId]);
DELETE t FROM [umbracoEngageAnalyticsPageviewCleanupQueue] t WHERE NOT EXISTS (SELECT 1 FROM [umbracoEngageAnalyticsPageview] r WHERE r.[id] = t.[pageviewId]);
DELETE t FROM [umbracoEngageAnalyticsPageviewPersonalizationSegment] t WHERE NOT EXISTS (SELECT 1 FROM [umbracoEngageAnalyticsPageview] r WHERE r.[id] = t.[pageviewId]) OR NOT EXISTS (SELECT 1 FROM [umbracoEngagePersonalizationSegment] r WHERE r.[id] = t.[segmentId]);
DELETE t FROM [umbracoEngageAnalyticsScrollDepth] t WHERE NOT EXISTS (SELECT 1 FROM [umbracoEngageAnalyticsPageview] r WHERE r.[id] = t.[pageviewId]);
DELETE t FROM [umbracoEngageAnalyticsSearchQuery] t WHERE NOT EXISTS (SELECT 1 FROM [umbracoEngageAnalyticsPageview] r WHERE r.[id] = t.[pageviewId]);
DELETE t FROM [umbracoEngageAnalyticsSession] t WHERE NOT EXISTS (SELECT 1 FROM [umbracoEngageAnalyticsVisitor] r WHERE r.[id] = t.[visitorId]);
DELETE t FROM [umbracoEngageAnalyticsTimeOnPage] t WHERE NOT EXISTS (SELECT 1 FROM [umbracoEngageAnalyticsPageview] r WHERE r.[id] = t.[pageviewId]);
DELETE t FROM [umbracoEngageAnalyticsUmbracoFormsSubmission] t WHERE NOT EXISTS (SELECT 1 FROM [umbracoEngageAnalyticsPageview] r WHERE r.[id] = t.[pageviewId]);
DELETE t FROM [umbracoEngageAnalyticsUmbracoFormsSubmissionAction] t WHERE NOT EXISTS (SELECT 1 FROM [umbracoEngageAnalyticsUmbracoFormsSubmission] r WHERE r.[id] = t.[submissionId]) OR NOT EXISTS (SELECT 1 FROM [umbracoEngageAnalyticsUmbracoFormsField] r WHERE r.[id] = t.[fieldId]);
DELETE t FROM [umbracoEngageAnalyticsUmbracoFormsSubmissionError] t WHERE NOT EXISTS (SELECT 1 FROM [umbracoEngageAnalyticsUmbracoFormsSubmission] r WHERE r.[id] = t.[submissionId]) OR NOT EXISTS (SELECT 1 FROM [umbracoEngageAnalyticsUmbracoFormsField] r WHERE r.[id] = t.[fieldId]);
DELETE t FROM [umbracoEngageAnalyticsVideoEvent] t WHERE NOT EXISTS (SELECT 1 FROM [umbracoEngageAnalyticsPageview] r WHERE r.[id] = t.[pageviewId]);
DELETE t FROM [umbracoEngageAnalyticsVideoStatistics] t WHERE NOT EXISTS (SELECT 1 FROM [umbracoEngageAnalyticsPageview] r WHERE r.[id] = t.[pageviewId]) OR NOT EXISTS (SELECT 1 FROM [umbracoEngageAnalyticsVideo] r WHERE r.[id] = t.[videoId]);
DELETE t FROM [umbracoEngageAnalyticsVisitorTypeBotVersion] t WHERE NOT EXISTS (SELECT 1 FROM [umbracoEngageAnalyticsVisitor] r WHERE r.[id] = t.[visitorId]) OR NOT EXISTS (SELECT 1 FROM [umbracoEngageAnalyticsVisitorTypeBot] r WHERE r.[id] = t.[botId]);
DELETE t FROM [umbracoEngageAnalyticsVisitorTypeMonitor] t WHERE NOT EXISTS (SELECT 1 FROM [umbracoEngageAnalyticsVisitor] r WHERE r.[id] = t.[visitorId]);
DELETE t FROM [umbracoEngageAnalyticsVisitorTypeSpam] t WHERE NOT EXISTS (SELECT 1 FROM [umbracoEngageAnalyticsVisitor] r WHERE r.[id] = t.[visitorId]);
DELETE t FROM [umbracoEngagePersonalizationAppliedPersonalizationContentType] t WHERE NOT EXISTS (SELECT 1 FROM [umbracoEngagePersonalizationAppliedPersonalization] r WHERE r.[id] = t.[personalizationId]);
DELETE t FROM [umbracoEngagePersonalizationAppliedPersonalizationUmbracoPageVariant] t WHERE NOT EXISTS (SELECT 1 FROM [umbracoEngagePersonalizationAppliedPersonalization] r WHERE r.[id] = t.[personalizationId]);
DELETE t FROM [umbracoEngagePersonalizationCampaign] t WHERE NOT EXISTS (SELECT 1 FROM [umbracoEngagePersonalizationCampaignGroup] r WHERE r.[id] = t.[campaignGroupId]);
DELETE t FROM [umbracoEngagePersonalizationCampaignGroupCustomerJourneyScoring] t WHERE NOT EXISTS (SELECT 1 FROM [umbracoEngagePersonalizationCampaignGroup] r WHERE r.[id] = t.[campaignGroupId]) OR NOT EXISTS (SELECT 1 FROM [umbracoEngagePersonalizationCustomerJourneyStep] r WHERE r.[id] = t.[customerJourneyStepId]);
DELETE t FROM [umbracoEngagePersonalizationCampaignGroupPersonaScoring] t WHERE NOT EXISTS (SELECT 1 FROM [umbracoEngagePersonalizationCampaignGroup] r WHERE r.[id] = t.[campaignGroupId]) OR NOT EXISTS (SELECT 1 FROM [umbracoEngagePersonalizationPersona] r WHERE r.[id] = t.[personaId]);
UPDATE t SET t.[customerJourneyStepId] = NULL FROM [umbracoEngagePersonalizationContentScoringCustomerJourneyStep] t WHERE t.[customerJourneyStepId] IS NOT NULL AND NOT EXISTS (SELECT 1 FROM [umbracoEngagePersonalizationCustomerJourneyStep] r WHERE r.[id] = t.[customerJourneyStepId]);
UPDATE t SET t.[personaId] = NULL FROM [umbracoEngagePersonalizationContentScoringPersona] t WHERE t.[personaId] IS NOT NULL AND NOT EXISTS (SELECT 1 FROM [umbracoEngagePersonalizationPersona] r WHERE r.[id] = t.[personaId]);
UPDATE t SET t.[customerJourneyGroupId] = NULL FROM [umbracoEngagePersonalizationCustomerJourneyStep] t WHERE t.[customerJourneyGroupId] IS NOT NULL AND NOT EXISTS (SELECT 1 FROM [umbracoEngagePersonalizationCustomerJourneyGroup] r WHERE r.[id] = t.[customerJourneyGroupId]);
DELETE t FROM [umbracoEngagePersonalizationGoalCustomerJourneyScoring] t WHERE NOT EXISTS (SELECT 1 FROM [umbracoEngageSettingsGoal] r WHERE r.[id] = t.[goalId]) OR NOT EXISTS (SELECT 1 FROM [umbracoEngagePersonalizationCustomerJourneyStep] r WHERE r.[id] = t.[customerJourneyStepId]);
DELETE t FROM [umbracoEngagePersonalizationGoalPersonaScoring] t WHERE NOT EXISTS (SELECT 1 FROM [umbracoEngageSettingsGoal] r WHERE r.[id] = t.[goalId]) OR NOT EXISTS (SELECT 1 FROM [umbracoEngagePersonalizationPersona] r WHERE r.[id] = t.[personaId]);
UPDATE t SET t.[personaGroupId] = NULL FROM [umbracoEngagePersonalizationPersona] t WHERE t.[personaGroupId] IS NOT NULL AND NOT EXISTS (SELECT 1 FROM [umbracoEngagePersonalizationPersonaGroup] r WHERE r.[id] = t.[personaGroupId]);
DELETE t FROM [umbracoEngagePersonalizationReferralGroupCustomerJourneyScoring] t WHERE NOT EXISTS (SELECT 1 FROM [umbracoEngagePersonalizationReferralGroup] r WHERE r.[id] = t.[referralGroupId]) OR NOT EXISTS (SELECT 1 FROM [umbracoEngagePersonalizationCustomerJourneyStep] r WHERE r.[id] = t.[customerJourneyStepId]);
DELETE t FROM [umbracoEngagePersonalizationReferralGroupPage] t WHERE NOT EXISTS (SELECT 1 FROM [umbracoEngageAnalyticsPage] r WHERE r.[id] = t.[pageId]) OR NOT EXISTS (SELECT 1 FROM [umbracoEngagePersonalizationReferralGroup] r WHERE r.[id] = t.[referralGroupId]);
DELETE t FROM [umbracoEngagePersonalizationReferralGroupPersonaScoring] t WHERE NOT EXISTS (SELECT 1 FROM [umbracoEngagePersonalizationReferralGroup] r WHERE r.[id] = t.[referralGroupId]) OR NOT EXISTS (SELECT 1 FROM [umbracoEngagePersonalizationPersona] r WHERE r.[id] = t.[personaId]);
DELETE t FROM [umbracoEngagePersonalizationSegmentRule] t WHERE NOT EXISTS (SELECT 1 FROM [umbracoEngagePersonalizationSegment] r WHERE r.[id] = t.[segmentId]);
DELETE t FROM [umbracoEngagePersonalizationVisitorSegmentSettings] t WHERE NOT EXISTS (SELECT 1 FROM [umbracoEngagePersonalizationSegment] r WHERE r.[id] = t.[segmentId]);
DELETE t FROM [umbracoEngageSettingsIpFilterIpAddress] t WHERE NOT EXISTS (SELECT 1 FROM [umbracoEngageSettingsIpFilter] r WHERE r.[id] = t.[ipFilterId]);

ALTER TABLE [umbracoEngageAbTestingAbTest] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [umbracoEngageAbTestingAbTestContentType] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [umbracoEngageAbTestingAbTestUmbracoPageVariant] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [umbracoEngageAbTestingAbTestVariant] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [umbracoEngageAbTestingAbTestVisitorToVariant] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [umbracoEngageAnalyticsAnnotationPageVariant] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [umbracoEngageAnalyticsBrowserVersion] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [umbracoEngageAnalyticsDevice] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [umbracoEngageAnalyticsGoalCompletion] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [umbracoEngageAnalyticsIpAddress] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [umbracoEngageAnalyticsIpLocation] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [umbracoEngageAnalyticsLinks] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [umbracoEngageAnalyticsOperatingSystemVersion] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [umbracoEngageAnalyticsPage] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [umbracoEngageAnalyticsPageEvent] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [umbracoEngageAnalyticsPageview] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [umbracoEngageAnalyticsPageviewAbTestVariant] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [umbracoEngageAnalyticsPageviewCleanupQueue] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [umbracoEngageAnalyticsPageviewPersonalizationSegment] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [umbracoEngageAnalyticsScrollDepth] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [umbracoEngageAnalyticsSearchQuery] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [umbracoEngageAnalyticsSession] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [umbracoEngageAnalyticsTimeOnPage] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [umbracoEngageAnalyticsUmbracoFormsSubmission] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [umbracoEngageAnalyticsUmbracoFormsSubmissionAction] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [umbracoEngageAnalyticsUmbracoFormsSubmissionError] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [umbracoEngageAnalyticsVideoEvent] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [umbracoEngageAnalyticsVideoStatistics] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [umbracoEngageAnalyticsVisitorTypeBotVersion] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [umbracoEngageAnalyticsVisitorTypeMonitor] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [umbracoEngageAnalyticsVisitorTypeSpam] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [umbracoEngagePersonalizationAppliedPersonalizationContentType] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [umbracoEngagePersonalizationAppliedPersonalizationUmbracoPageVariant] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [umbracoEngagePersonalizationCampaign] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [umbracoEngagePersonalizationCampaignGroupCustomerJourneyScoring] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [umbracoEngagePersonalizationCampaignGroupPersonaScoring] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [umbracoEngagePersonalizationContentScoringCustomerJourneyStep] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [umbracoEngagePersonalizationContentScoringPersona] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [umbracoEngagePersonalizationCustomerJourneyStep] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [umbracoEngagePersonalizationGoalCustomerJourneyScoring] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [umbracoEngagePersonalizationGoalPersonaScoring] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [umbracoEngagePersonalizationPersona] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [umbracoEngagePersonalizationReferralGroupCustomerJourneyScoring] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [umbracoEngagePersonalizationReferralGroupPage] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [umbracoEngagePersonalizationReferralGroupPersonaScoring] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [umbracoEngagePersonalizationSegmentRule] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [umbracoEngagePersonalizationVisitorSegmentSettings] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [umbracoEngageSettingsIpFilterIpAddress] WITH CHECK CHECK CONSTRAINT ALL;